-- Canonical Able101 fixtures table schema (reference only)
-- This is documentation, do not run blindly against production DB

CREATE TABLE fixtures (
  fixture_id INTEGER PRIMARY KEY,
  date TEXT,
  league_id INTEGER,
  season INTEGER,
  home_team TEXT,
  away_team TEXT,
  league_name TEXT,
  country TEXT,
  home_score INTEGER,
  away_score INTEGER,
  home_win INTEGER,
  draw INTEGER,
  away_win INTEGER,
  over_1_5 INTEGER,
  over_2_5 INTEGER,
  btts INTEGER,
  home_shots_on_goal REAL,
  home_shots_off_goal REAL,
  home_total_shots REAL,
  home_blocked_shots REAL,
  home_shots_insidebox REAL,
  home_shots_outsidebox REAL,
  home_fouls REAL,
  home_corner_kicks REAL,
  home_offsides REAL,
  home_ball_possession REAL,
  home_yellow_cards REAL,
  home_red_cards REAL,
  home_goalkeeper_saves REAL,
  home_total_passes REAL,
  home_passes_accurate REAL,
  home_passes_% REAL,
  away_shots_on_goal REAL,
  away_shots_off_goal REAL,
  away_total_shots REAL,
  away_blocked_shots REAL,
  away_shots_insidebox REAL,
  away_shots_outsidebox REAL,
  away_fouls REAL,
  away_corner_kicks REAL,
  away_offsides REAL,
  away_ball_possession REAL,
  away_yellow_cards REAL,
  away_red_cards REAL,
  away_goalkeeper_saves REAL,
  away_total_passes REAL,
  away_passes_accurate REAL,
  away_passes_% REAL,
  last_updated TEXT
);
